---
title: "UMAP_positive_control"
author: "Chenxin Li"
date: "2023-08-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages
```{r}
library(tidyverse)
library(patchwork)
library(umap)
library(viridis)
library(RColorBrewer)
library(rcartocolor)
```
# Data
```{r}
set.seed(999)
```
 
## Simulate data 
```{r}
my_data <- expand.grid(
  x = 1:21,
  y = 1:21) %>% 
  mutate(
    group_x = case_when(
      x <= 6 ~ 1,
      x > 6 & x <= 11 ~ 2,
      x > 11 & x <= 15 ~ 3,
      x > 15 & x <= 18 ~ 4,
      x > 18 & x <= 20 ~ 5,
      x > 20 ~ 6
    )
  ) %>% 
  mutate(
    group_y = case_when(
      y <= 6 ~ 1,
      y > 6 & y <= 11 ~ 2,
      y > 11 & y <= 15 ~ 3,
      y > 15 & y <= 18 ~ 4,
      y > 18 & y <= 20 ~ 5,
      y > 20 ~ 6
    )
  ) %>%
  mutate(group_sq = (group_x - group_y)^2) %>% 
  mutate(
    fill = case_when(
      group_sq == 0 ~ 2,
      group_sq == 1 ~ 0.5,
      group_sq == 4 ~ 0,
      group_sq == 9 ~ -0.5,
      group_sq == 16 ~ -1,
      group_sq == 25 ~ -2
    )
  ) %>%
  cbind(
    noise = rnorm(n = nrow(.), mean = 0, sd = 0.25)
  ) %>% 
  mutate(fill2 = fill + noise)

my_data
```

## Raw data heat map 
```{r}
heatmap <- my_data %>% 
  ggplot(aes(x = x , y = y)) +
  facet_grid(group_y ~ group_x, space = "free", scales = "free") +
  geom_tile(aes(fill = fill2)) +
  scale_fill_gradientn(colors = rev(brewer.pal(11, "RdBu")),
                      limits = c(-max(my_data$fill2), max(my_data$fill2))) +
  labs(x = NULL,
       y = NULL)+
  theme_minimal()+
  theme(
    strip.text = element_blank(),
    strip.background = element_blank(),
    panel.grid = element_blank(),
    axis.text = element_blank(),
    legend.position = "none"
  )

strip_left <- my_data %>% 
  filter(x == 1) %>% 
  ggplot(aes(x = 1, y = y)) +
  facet_grid(group_y ~ group_x, space = "free", scales = "free") + 
  geom_tile(aes(fill = as.factor(group_y))) +
  scale_fill_manual(values = viridis(n = 6)) +
  labs(x = NULL,
       y = NULL)+
  theme_minimal()+
  theme(
    strip.text = element_blank(),
    strip.background = element_blank(),
    panel.grid = element_blank(),
    axis.text = element_blank(),
    legend.position = "none"
    )


strip_bottom <- my_data %>% 
  filter(y == 1) %>% 
  ggplot(aes(x = x, y = 1)) +
  facet_grid(group_y ~ group_x, space = "free", scales = "free") + 
  geom_tile(aes(fill = group_x)) +
  scale_fill_gradientn(colors = rev(carto_pal(7, "Magenta"))) +
  labs(x = NULL,
       y = NULL)+
  theme_minimal()+
  theme(
    strip.text = element_blank(),
    strip.background = element_blank(),
    panel.grid = element_blank(),
    axis.text = element_blank(),
    legend.position = "none"
  )

raw_heatmap <- wrap_plots(
  heatmap +
  labs(tag = "A"), strip_left,
  strip_bottom, 
  nrow = 2, ncol = 2,
  widths = c(1, 0.04),
  heights = c(1, 0.04)
)

raw_heatmap
```


# PCA 
```{r}
my_data_wide <- my_data %>% 
  select(x, y, fill2, group_y) %>% 
  pivot_wider(names_from = x, values_from = fill2)

head(my_data_wide)
```

```{r}
my_pca <- prcomp(my_data_wide[, -c(1,2)])
my_pc_importance <- summary(my_pca)$importance

my_pc_importance
```


## Graph PCA
```{r}
pca_12 <- my_pca$x %>% 
  as.data.frame() %>% 
  cbind(my_data_wide) %>% 
  ggplot(aes(x = PC1, y = PC2)) +
  geom_point(aes(color = as.factor(group_y)),
             size = 1.5, alpha = 0.8) +
  scale_color_manual(values = viridis(n = 6)) +
  labs(x = paste0("PC1: ", signif(my_pc_importance[2, 1]*100, 2), "% variance"),
       y = paste0("PC2: ", signif(my_pc_importance[2, 2]*100, 2), "% variance"),
       color = "group") +
  theme_bw()
   

pca_12
```
```{r}
pca_23 <- my_pca$x %>% 
  as.data.frame() %>% 
  cbind(my_data_wide) %>% 
  ggplot(aes(x = PC2, y = PC3)) +
  geom_point(aes(color = as.factor(group_y)),
             size = 1.5, alpha = 0.8) +
  scale_color_manual(values = viridis(n = 6)) +
  labs(x = paste0("PC2: ", signif(my_pc_importance[2, 2]*100, 2), "% variance"),
       y = paste0("PC3: ", signif(my_pc_importance[2, 3]*100, 2), "% variance"),
       color = "group") +
  theme_bw()
   

pca_23
```

```{r}
pca_34 <- my_pca$x %>% 
  as.data.frame() %>% 
  cbind(my_data_wide) %>% 
  ggplot(aes(x = PC3, y = PC4)) +
  geom_point(aes(color = as.factor(group_y)),
             size = 1.5, alpha = 0.8) +
  scale_color_manual(values = viridis(n = 6)) +
  labs(x = paste0("PC3: ", signif(my_pc_importance[2, 3]*100, 2), "% variance"),
       y = paste0("PC4: ", signif(my_pc_importance[2, 4]*100, 2), "% variance"),
       color = "group") +
  theme_bw()
   

pca_34
```
```{r}
pca_45 <- my_pca$x %>% 
  as.data.frame() %>% 
  cbind(my_data_wide) %>% 
  ggplot(aes(x = PC4, y = PC5)) +
  geom_point(aes(color = as.factor(group_y)),
             size = 1.5, alpha = 0.8) +
  scale_color_manual(values = viridis(n = 6)) +
  labs(x = paste0("PC4: ", signif(my_pc_importance[2, 4]*100, 2), "% variance"),
       y = paste0("PC5: ", signif(my_pc_importance[2, 5]*100, 2), "% variance"),
       color = "group") +
  theme_bw()
   

pca_45
```

# UMAP 
```{r}
my_umap <- umap(d = my_pca$x)
```

## Graph UMAP 
```{r}
UMAP_plot <- my_umap$layout %>% 
  as.data.frame() %>% 
  cbind(my_data_wide) %>% 
  ggplot(aes(x = V1, y = V2)) +
  geom_point(aes(color = as.factor(group_y)),
             size = 1.5, alpha = 0.8) +
  scale_color_manual(values = viridis(n = 6)) +
  labs(x = "UMAP1",
       y = "UMAP2",
       color = "group") +
  theme_bw() +
  theme(panel.grid = element_blank())

UMAP_plot
```

# Assemble plot 
```{r}
wrap_plots(
  raw_heatmap,
  pca_12 +
    labs(tag = "B"), 
  pca_23 +
    labs(tag = "C"),
  pca_34 +
    labs(tag = "D"), 
  pca_45 +
    labs(tag = "E"),
  UMAP_plot +
    labs(tag = "F"),
  design = c("ABCF
              ADEF"),
  widths = c(1.2, 0.75, 0.75, 1),
  guides = "collect"
)

ggsave("raw_vs_PCA_vs_UMAP.svg", height = 3.5, width = 10)
ggsave("raw_vs_PCA_vs_UMAP.png", height = 3.5, width = 10)
```

